[[redirects]]
  from = "/"
  to = "https://github.com/kizzx2/solana-sign-with-payment"
  force = true
  status = 301

[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/verify"
  status = 200

[[redirects]]
  from = "/init"
  to = "/.netlify/functions/init"
  status = 200

[template.environment]
  JWK_PRIAVTE_KEY = "JWK key (JSON formatted)"