[[redirects]]
  from = "/"
  to = "https://github.com/kizzx2/solana-sign-with-payment"
  force = true
  status = 301

[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/verify"
  status = 200

[[redirects]]
  from = "/init"
  to = "/.netlify/functions/init"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    
[template.environment]
  JWK_PRIVATE_KEY = "JWK key (JSON formatted)"
